default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  port: 5432
  pool: 5

development:
  <<: *default
  database: docker-rails_development

test:
  <<: *default
  database: docker-rails_test
